CREATE DATABASE DEVICE_IOT;
USE DEVICE_IOT;
CREATE TABLE USERS
(
	USER_ID varchar(30) PRIMARY KEY,
	USER_PASS varchar(30) NOT NULL
);

CREATE TABLE DEVICES
(
	DV_ID varchar(30) PRIMARY KEY,
	USER_ID varchar(30),
	STATUS bit
);

ALTER TABLE DEVICES ADD CONSTRAINT FK_DEVICES_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID);

/*Insert du lieu*/
DELETE FROM USERS;

INSERT INTO USERS (USER_ID, USER_PASS)values('CEEC','ce.uit.edu.vn');

DELETE FROM DEVICES;

INSERT INTO DEVICES (DV_ID, USER_ID, STATUS)values('LED13','CEEC',0);

INSERT INTO DEVICES (DV_ID, USER_ID, STATUS)values('RELAY','CEEC',0);

/*Thay doi du lieu*/
UPDATE DEVICES SET STATUS=1 WHERE DV_ID='LED13';